import path from 'path';
import fs from 'fs-extra';
import pc from 'picocolors';
import type { AppConfig } from '../types.js';

export interface GeneratorOptions {
  dryRun?: boolean;
}

export async function generateAndroid(cwd: string, config: AppConfig, options: GeneratorOptions = {}) {
  const gradlePath = path.join(cwd, 'android', 'app', 'build.gradle');
  const manifestPath = path.join(cwd, 'android', 'app', 'src', 'main', 'AndroidManifest.xml');

  if (!fs.existsSync(gradlePath)) {
    throw new Error(`Android Gradle file not found at ${gradlePath}. Ensure you are in a React Native project directory.`);
  }

  let gradleContent = await fs.readFile(gradlePath, 'utf8');

  // 1. Generate the product flavors block
  let flavorBlock = '// RNFM_START\n';
  flavorBlock += '    // This section is autogenerated by React Native Flavor Manager. Do not edit.\n';
  flavorBlock += '    flavorDimensions "default"\n';
  flavorBlock += '    productFlavors {\n';

  for (const [flavorName, flavor] of Object.entries(config.flavors)) {
    flavorBlock += `        ${flavorName} {\n`;
    flavorBlock += '            dimension "default"\n';

    if (flavor.packageName) {
      flavorBlock += `            applicationId "${flavor.packageName}"\n`;
    }
    if (flavor.version) {
      flavorBlock += `            versionName "${flavor.version}"\n`;
    }
    if (flavor.versionCode) {
      flavorBlock += `            versionCode ${flavor.versionCode}\n`;
    }

    const resolvedAppName = flavor.appName || flavor.displayName || flavorName;
    flavorBlock += `            manifestPlaceholders = [appName: "${resolvedAppName}"]\n`;

    flavorBlock += '        }\n';
  }

  flavorBlock += '    }\n';
  flavorBlock += '    // RNFM_END';

  // 2. Inject or replace the block in build.gradle
  const startMarker = '// RNFM_START';
  const endMarker = '// RNFM_END';

  const startIndex = gradleContent.indexOf(startMarker);
  const endIndex = gradleContent.indexOf(endMarker);

  let newGradleContent = '';
  if (startIndex !== -1 && endIndex !== -1) {
    // Replace existing block exactly in place
    const regex = /\/\/ RNFM_START[\s\S]*?\/\/ RNFM_END/;
    newGradleContent = gradleContent.replace(regex, flavorBlock);
  } else {
    // Inject brand new block immediately after defaultConfig { ... } block
    const dcRegex = /defaultConfig\s*\{[^}]*\}/;
    const match = gradleContent.match(dcRegex);
    if (!match) {
      // Fallback to top of android block
      const androidRegex = /android\s*\{/;
      const aMatch = gradleContent.match(androidRegex);
      if (!aMatch) {
        throw new Error("Could not find 'android {' block in android/app/build.gradle");
      }
      const insertIndex = aMatch.index! + aMatch[0].length;
      const before = gradleContent.substring(0, insertIndex);
      const after = gradleContent.substring(insertIndex);
      newGradleContent = before + '\n' + flavorBlock + '\n' + after;
    } else {
      const insertIndex = match.index! + match[0].length;
      const before = gradleContent.substring(0, insertIndex);
      const after = gradleContent.substring(insertIndex);
      newGradleContent = before + '\n\n' + flavorBlock + '\n' + after;
    }
  }

  // Ensure default appName placeholder exists in defaultConfig to prevent compilation failures
  // if no flavor is selected (or during default builds).
  if (!newGradleContent.includes('manifestPlaceholders') || !newGradleContent.includes('appName')) {
    const defaultConfigRegex = /defaultConfig\s*\{/;
    const dcMatch = newGradleContent.match(defaultConfigRegex);
    if (dcMatch) {
      const dcInsertIndex = dcMatch.index! + dcMatch[0].length;
      const beforeDC = newGradleContent.substring(0, dcInsertIndex);
      const afterDC = newGradleContent.substring(dcInsertIndex);
      newGradleContent = beforeDC + '\n        manifestPlaceholders = [appName: "React Native App"]' + afterDC;
    }
  }

  // 3. Update AndroidManifest.xml if it uses the hardcoded app_name string
  let manifestModified = false;
  let newManifestContent = '';

  if (fs.existsSync(manifestPath)) {
    const manifestContent = await fs.readFile(manifestPath, 'utf8');
    if (manifestContent.includes('android:label="@string/app_name"')) {
      newManifestContent = manifestContent.replace(
        'android:label="@string/app_name"',
        'android:label="${appName}"'
      );
      manifestModified = true;
    }
  }

  // 4. Write changes (or print in dry-run mode)
  if (options.dryRun) {
    console.log(pc.bold('\n[PROPOSED CHANGES] android/app/build.gradle:'));
    // Show diff preview of gradle flavors block
    console.log(pc.green(flavorBlock));

    if (manifestModified) {
      console.log(pc.bold('[PROPOSED CHANGES] android/app/src/main/AndroidManifest.xml:'));
      console.log(pc.red('- android:label="@string/app_name"'));
      console.log(pc.green('+ android:label="${appName}"'));
    }
  } else {
    // Write Gradle
    await fs.writeFile(gradlePath, newGradleContent, 'utf8');
    console.log(pc.green('✔ Updated android/app/build.gradle with product flavors'));

    // Write Manifest
    if (manifestModified && newManifestContent) {
      await fs.writeFile(manifestPath, newManifestContent, 'utf8');
      console.log(pc.green('✔ Updated AndroidManifest.xml to use dynamic appName placeholder'));
    }
  }
}
