import path from 'path';
import fs from 'fs-extra';
import pc from 'picocolors';
import type { AppConfig } from '../types.js';

export interface IOSOptions {
  dryRun?: boolean;
}

export function findXcodeProject(cwd: string): { projectPath: string; projectName: string } | null {
  const iosDir = path.join(cwd, 'ios');
  if (!fs.existsSync(iosDir)) return null;

  const files = fs.readdirSync(iosDir);
  const xcodeproj = files.find(f => f.endsWith('.xcodeproj'));
  if (!xcodeproj) return null;

  return {
    projectPath: path.join(iosDir, xcodeproj),
    projectName: path.basename(xcodeproj, '.xcodeproj'),
  };
}

export async function generateIOS(cwd: string, config: AppConfig, options: IOSOptions = {}) {
  const xcodeInfo = findXcodeProject(cwd);
  if (!xcodeInfo) {
    // If not an iOS project, skip iOS generation quietly
    return;
  }

  const { projectPath, projectName } = xcodeInfo;
  const pbxprojPath = path.join(projectPath, 'project.pbxproj');

  if (!fs.existsSync(pbxprojPath)) return;

  const flavorNames = Object.keys(config.flavors);
  if (flavorNames.length === 0) return;

  // We default to the first flavor for the active configuration
  const activeFlavor = flavorNames[0];

  // 1. Generate active configuration: ios/RNFMConfig.xcconfig
  const activeFlavorConfig = config.flavors[activeFlavor];
  const appDisplayName = activeFlavorConfig.appName || activeFlavorConfig.displayName || projectName;
  const bundleId = activeFlavorConfig.bundleId || `com.demo.${activeFlavor}`;

  let xcconfigContent = `// Autogenerated by React Native Flavor Manager. Do not edit.\n`;
  xcconfigContent += `PRODUCT_BUNDLE_IDENTIFIER = ${bundleId}\n`;
  xcconfigContent += `PRODUCT_NAME = ${appDisplayName}\n`;
  xcconfigContent += `ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon-${activeFlavor}\n`;

  const xcconfigPath = path.join(cwd, 'ios', 'RNFMConfig.xcconfig');

  if (options.dryRun) {
    console.log(pc.bold('\n[PROPOSED CHANGES] ios/RNFMConfig.xcconfig:'));
    console.log(pc.green(xcconfigContent));
  } else {
    await fs.writeFile(xcconfigPath, xcconfigContent, 'utf8');
    console.log(pc.green('✔ Updated ios/RNFMConfig.xcconfig'));
  }

  // 2. Extract Main target BlueprintIdentifier from project.pbxproj
  let blueprintId = '13B07F861A680F5B00A75B9A'; // Default RN blueprint ID fallback
  try {
    const pbxprojContent = await fs.readFile(pbxprojPath, 'utf8');
    // Regex matches 24 hex char ID associated with the project's native target
    // e.g. 13B07F861A680F5B00A75B9A /* ProjectName */ = { isa = PBXNativeTarget; ...
    const escapedProjectName = projectName.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
    const targetRegex = new RegExp(`([A-F0-9]{24})\\s*\\/\\*\\s*${escapedProjectName}\\s*\\*\\/\\s*=\\s*\\{\\s*isa\\s*=\\s*PBXNativeTarget;`);
    const match = pbxprojContent.match(targetRegex);
    if (match && match[1]) {
      blueprintId = match[1];
    }
  } catch {}

  // 3. Generate Xcode scheme files for all flavors
  const schemesDir = path.join(projectPath, 'xcshareddata', 'xcschemes');

  if (options.dryRun) {
    console.log(pc.bold('\n[PROPOSED XCODE SCHEMES]'));
  } else {
    await fs.ensureDir(schemesDir);
  }

  for (const flavorName of flavorNames) {
    const schemeName = `${projectName}-${flavorName}`;
    const schemeFilePath = path.join(schemesDir, `${schemeName}.xcscheme`);

    // Build the Scheme XML
    const schemeXml = `<?xml version="1.0" encoding="UTF-8"?>
<Scheme
   LastUpgradeVersion = "1500"
   version = "1.7">
   <BuildAction
      parallelizeBuildables = "YES"
      buildImplicitDependencies = "YES">
      <BuildActionEntries>
         <BuildActionEntry
            buildForTesting = "YES"
            buildForRunning = "YES"
            buildForProfiling = "YES"
            buildForArchiving = "YES"
            buildForAnalyzing = "YES">
            <BuildableReference
               BuildableIdentifier = "primary"
               BlueprintIdentifier = "${blueprintId}"
               BuildableName = "${projectName}.app"
               BlueprintName = "${projectName}"
               ReferencedContainer = "container:${projectName}.xcodeproj">
            </BuildableReference>
         </BuildActionEntry>
      </BuildActionEntries>
   </BuildAction>
   <LaunchAction
      buildConfiguration = "Release"
      selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
      selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
      launchStyle = "0"
      useCustomWorkingDirectory = "NO"
      ignoresPersistentStateOnLaunch = "NO"
      debugDocumentVersioning = "YES"
      debugServiceExtension = "internal"
      allowLocationSimulation = "YES">
      <BuildableProductRunnable
         runnableDebuggingMode = "0">
         <BuildableReference
            BuildableIdentifier = "primary"
            BlueprintIdentifier = "${blueprintId}"
            BuildableName = "${projectName}.app"
            BlueprintName = "${projectName}"
            ReferencedContainer = "container:${projectName}.xcodeproj">
         </BuildableReference>
      </BuildableProductRunnable>
   </LaunchAction>
</Scheme>
`;

    if (options.dryRun) {
      console.log(pc.gray(`  Create scheme: ios/${projectName}.xcodeproj/xcshareddata/xcschemes/${schemeName}.xcscheme`));
    } else {
      await fs.writeFile(schemeFilePath, schemeXml, 'utf8');
      console.log(pc.green(`✔ Created Xcode Scheme: ${schemeName}`));
    }
  }

  // 4. Connect build configurations to RNFMConfig.xcconfig automatically inside project.pbxproj
  // We locate all build configurations and check if baseConfigurationReference is set.
  // To keep it simple, robust, and idempotent, we check if project.pbxproj already has RNFMConfig.xcconfig linked.
  if (!options.dryRun) {
    try {
      let pbxprojContent = await fs.readFile(pbxprojPath, 'utf8');
      
      // If project has not been linked to RNFMConfig yet, let's inject config link
      if (!pbxprojContent.includes('RNFMConfig.xcconfig')) {
        // Use node-xcode to link base configuration reference programmatically
        const xcode = (await import('xcode')).default;
        const project = xcode.project(pbxprojPath);
        project.parseSync();

        // 1. Add file reference to project
        const fileRef = project.addFile('RNFMConfig.xcconfig', null, { lastKnownFileType: 'text.xcconfig' });
        
        if (fileRef) {
          // 2. Associate build configurations with this file reference
          const buildConfigs = project.hash.project.objects.XCBuildConfiguration;
          for (const key of Object.keys(buildConfigs)) {
            const configObj = buildConfigs[key];
            if (configObj && typeof configObj === 'object' && configObj.buildSettings) {
              // Set baseConfigurationReference to the file reference UUID
              configObj.baseConfigurationReference = fileRef.fileRef;
              configObj.baseConfigurationReference_comment = 'RNFMConfig.xcconfig';
            }
          }

          // Write back the modified project pbxproj
          await fs.writeFile(pbxprojPath, project.writeSync(), 'utf8');
          console.log(pc.green('✔ Linked RNFMConfig.xcconfig base configuration references in project.pbxproj'));
        }
      }
    } catch (err: any) {
      console.log(pc.yellow(`⚠ Could not automatically link project.pbxproj: ${err.message}`));
      console.log('You may need to associate Base Configurations to RNFMConfig.xcconfig manually in Xcode.');
    }
  }
}

/**
 * Updates the active build configuration values inside RNFMConfig.xcconfig
 */
export async function activateIOSConfig(cwd: string, flavorName: string) {
  const xcodeInfo = findXcodeProject(cwd);
  if (!xcodeInfo) return;

  const { projectName } = xcodeInfo;
  const loaded = await loadConfig(cwd);
  const normalized = configNormalizer(loaded.config);

  const flavor = normalized.flavors[flavorName];
  if (!flavor) return;

  const appDisplayName = flavor.appName || flavor.displayName || projectName;
  const bundleId = flavor.bundleId || `com.demo.${flavorName}`;

  let xcconfigContent = `// Autogenerated by React Native Flavor Manager. Do not edit.\n`;
  xcconfigContent += `PRODUCT_BUNDLE_IDENTIFIER = ${bundleId}\n`;
  xcconfigContent += `PRODUCT_NAME = ${appDisplayName}\n`;
  xcconfigContent += `ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon-${flavorName}\n`;

  const xcconfigPath = path.join(cwd, 'ios', 'RNFMConfig.xcconfig');
  await fs.writeFile(xcconfigPath, xcconfigContent, 'utf8');
  console.log(pc.green(`✔ Activated iOS Build configuration for flavor '${flavorName}'`));
}

// Simple config normalizer helper
function configNormalizer(config: any): any {
  const normalizedFlavors: Record<string, any> = {};
  for (const [flavorName, flavor] of Object.entries(config.flavors)) {
    const f: any = flavor;
    normalizedFlavors[flavorName] = {
      appName: f.appName || f.displayName,
      bundleId: f.bundleId || f.packageName,
    };
  }
  return { flavors: normalizedFlavors };
}
